name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti jika branch utamamu bukan "main"

permissions:
  contents: read
  pages: write
  id-token: write

# Step 1: Build the project and upload artifact
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

# Step 2: Deploy to GitHub Pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
